/**
 * Foreign AI instruction file detector.
 *
 * isForeignFile()         — returns true if a file has no openskulls section markers
 * scanForeignFiles()      — scans well-known AI instruction file paths at a repo root
 * detectForeignSkillFiles() — finds .claude/commands/*.md files not managed by openskulls
 */

import { readFile, readdir } from 'node:fs/promises'
import { join } from 'node:path'
import { parseChunks } from '../generators/merge.js'
import { ForeignFileContext, ForeignFileScan } from './foreign-file-types.js'

// ─── Well-known AI instruction file paths ─────────────────────────────────────

/** Paths (relative to repo root) that openskulls can generate and manage. */
export const MANAGED_INSTRUCTION_FILES = [
  'CLAUDE.md',
  'AGENTS.md',
  '.github/copilot-instructions.md',
  '.cursor/rules/project.mdc',
] as const

// ─── Detection ────────────────────────────────────────────────────────────────

/**
 * Returns true if the file content has no openskulls section markers —
 * i.e. the file exists but was not generated by openskulls.
 */
export function isForeignFile(content: string): boolean {
  const chunks = parseChunks(content)
  return chunks.every((c) => c.kind !== 'managed')
}

// ─── Scanner ──────────────────────────────────────────────────────────────────

/**
 * Scan `repoRoot` for foreign AI instruction files and unmanaged skill files.
 *
 * - Checks each path in MANAGED_INSTRUCTION_FILES.
 * - Scans .claude/commands/ for skill files not emitted by openskulls.
 *
 * Files that don't exist are silently skipped.
 * Files that exist but have openskulls section markers are not reported as foreign.
 */
export async function scanForeignFiles(repoRoot: string): Promise<ForeignFileScan> {
  const foreignFiles: ForeignFileContext[] = []
  const foreignSkills: string[] = []

  // Check well-known instruction file paths
  for (const relPath of MANAGED_INSTRUCTION_FILES) {
    const absPath = join(repoRoot, relPath)
    let content: string
    try {
      content = await readFile(absPath, 'utf-8')
    } catch {
      continue  // File doesn't exist — skip
    }
    if (isForeignFile(content)) {
      foreignFiles.push(ForeignFileContext.parse({ path: relPath, content }))
    }
  }

  // Scan .claude/commands/ for unmanaged skill files
  const unmanaged = await detectForeignSkillFiles(repoRoot)
  foreignSkills.push(...unmanaged)

  return ForeignFileScan.parse({ foreignFiles, foreignSkills })
}

/**
 * Scan `.claude/commands/*.md` and return relative paths of files that
 * are NOT managed by openskulls (i.e. have no openskulls section markers
 * AND are not in .claude/skills/ subdirectories).
 *
 * Note: openskulls writes skill files to .claude/skills/<id>/SKILL.md,
 * not to .claude/commands/ directly. Files found in .claude/commands/ that
 * were NOT written by openskulls are considered foreign.
 */
export async function detectForeignSkillFiles(repoRoot: string): Promise<string[]> {
  const commandsDir = join(repoRoot, '.claude', 'commands')
  let entries: string[]
  try {
    entries = await readdir(commandsDir)
  } catch {
    return []  // Directory doesn't exist
  }

  const foreign: string[] = []
  for (const entry of entries) {
    if (!entry.endsWith('.md')) continue
    const absPath = join(commandsDir, entry)
    let content: string
    try {
      content = await readFile(absPath, 'utf-8')
    } catch {
      continue
    }
    // Files in .claude/commands/ were not generated by openskulls
    // (openskulls uses .claude/skills/<id>/SKILL.md for AI skills,
    //  and .claude/commands/ only for built-in run-tests/commit skills
    //  which do have a specific content structure).
    // Any .md in .claude/commands/ that has no openskulls markers is foreign.
    if (isForeignFile(content)) {
      foreign.push(`.claude/commands/${entry}`)
    }
  }
  return foreign
}
