/**
 * AI-powered foreign file importer.
 *
 * Reads an existing AI instruction file (CLAUDE.md, AGENTS.md, etc.) that
 * was not generated by openskulls and extracts its rules, conventions, and
 * architectural constraints via an AI call.
 *
 * The extracted content is merged into the `qa` map so it flows through the
 * existing init pipeline and is reflected in all generated output.
 *
 * Prompt injection is prevented by wrapping file content in delimiters:
 *   --- FILE CONTENT START --- / --- FILE CONTENT END ---
 */

import Handlebars from 'handlebars'
import { detectAICLI, invokeAICLI, stripJsonFences, type AICLIAdapter, type VerboseLogger } from './ai-collector.js'
import { ForeignFileContext } from './foreign-file-types.js'
import { FOREIGN_FILE_IMPORT_TEMPLATE } from '../../generated/templates.js'

// ─── Template ─────────────────────────────────────────────────────────────────

const hbs = Handlebars.create()
const COMPILED = hbs.compile(FOREIGN_FILE_IMPORT_TEMPLATE, { noEscape: true })

// ─── Prompt builder ───────────────────────────────────────────────────────────

/**
 * Build the AI prompt for extracting rules from a foreign file.
 * File content is wrapped in delimiters to prevent prompt injection.
 */
export function buildForeignFilePrompt(filePath: string, fileContent: string): string {
  return COMPILED({ filePath, fileContent })
}

// ─── Single-file import ───────────────────────────────────────────────────────

/**
 * Import a single foreign file: invoke the AI CLI and return an enriched
 * ForeignFileContext with extracted rules, conventions, and constraints.
 *
 * Non-fatal: if the AI call or parse fails, returns the original context
 * unchanged (no extracted data, no summary).
 */
export async function importForeignFile(
  file: { path: string; content: string },
  adapter?: AICLIAdapter,
  logger?: VerboseLogger,
): Promise<ForeignFileContext> {
  const cliCommand = adapter ?? await detectAICLI()
  const prompt = buildForeignFilePrompt(file.path, file.content)

  try {
    const raw = await invokeAICLI(cliCommand, prompt, 60_000, logger)
    const parsed = JSON.parse(stripJsonFences(raw))
    return ForeignFileContext.parse({
      path: file.path,
      content: file.content,
      extractedConventions: parsed.extractedConventions ?? [],
      extractedRules: parsed.extractedRules ?? [],
      extractedConstraints: parsed.extractedConstraints ?? [],
      summary: parsed.summary,
    })
  } catch {
    // Return unenriched context on any failure
    return ForeignFileContext.parse({ path: file.path, content: file.content })
  }
}

// ─── Multi-file import ────────────────────────────────────────────────────────

/**
 * Import multiple foreign files sequentially. Failures are non-fatal per file.
 * Returns enriched ForeignFileContext[] in the same order as input.
 */
export async function importForeignFiles(
  files: Array<{ path: string; content: string }>,
  adapter?: AICLIAdapter,
  logger?: VerboseLogger,
): Promise<ForeignFileContext[]> {
  const results: ForeignFileContext[] = []
  for (const file of files) {
    results.push(await importForeignFile(file, adapter, logger))
  }
  return results
}

// ─── QA map integration ───────────────────────────────────────────────────────

/**
 * Merge extracted foreign file content into a qa map for the init pipeline.
 *
 * Keys used:
 *   foreign_file_conventions  — semicolon-separated list of extracted conventions
 *   foreign_file_rules        — semicolon-separated list of extracted rules
 *   foreign_file_constraints  — semicolon-separated list of extracted constraints
 *   foreign_file_summary      — comma-separated summaries from all files
 *
 * Existing qa values are preserved and not overwritten.
 */
export function mergeForeignContextIntoQA(
  foreignFiles: ForeignFileContext[],
  existingQA: Record<string, string> = {},
): Record<string, string> {
  const allConventions: string[] = []
  const allRules: string[] = []
  const allConstraints: string[] = []
  const allSummaries: string[] = []

  for (const file of foreignFiles) {
    allConventions.push(...file.extractedConventions)
    allRules.push(...file.extractedRules)
    allConstraints.push(...file.extractedConstraints)
    if (file.summary) allSummaries.push(file.summary)
  }

  const result: Record<string, string> = { ...existingQA }

  if (allConventions.length > 0) {
    result['foreign_file_conventions'] = allConventions.join('; ')
  }
  if (allRules.length > 0) {
    result['foreign_file_rules'] = allRules.join('; ')
  }
  if (allConstraints.length > 0) {
    result['foreign_file_constraints'] = allConstraints.join('; ')
  }
  if (allSummaries.length > 0) {
    result['foreign_file_summary'] = allSummaries.join(', ')
  }

  return result
}
