#!/usr/bin/env bun
/**
 * Prebuild script — inlines all .hbs template files into src/generated/templates.ts
 * so the compiled binary has no runtime filesystem dependency on templates/.
 *
 * Run: bun scripts/gen-templates.ts
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { join } from 'node:path'

const ROOT = new URL('..', import.meta.url).pathname
const pkg = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf-8')) as { version: string }

const TEMPLATES: Record<string, string> = {
  ANALYSIS:      join(ROOT, 'templates/prompts/analysis.md.hbs'),
  SKILLS:        join(ROOT, 'templates/prompts/skills.md.hbs'),
  QUESTIONNAIRE: join(ROOT, 'templates/prompts/questionnaire.md.hbs'),
  ARCHITECT:     join(ROOT, 'templates/prompts/architect.md.hbs'),
  METHODOLOGY:   join(ROOT, 'templates/prompts/methodology.md.hbs'),
  CLAUDE_MD:     join(ROOT, 'templates/claude-code/CLAUDE.md.hbs'),
}

const outDir = join(ROOT, 'src/generated')
mkdirSync(outDir, { recursive: true })

let out = '// Auto-generated by scripts/gen-templates.ts — do not edit\n\n'
out += `export const VERSION: string = ${JSON.stringify(pkg.version)}\n\n`
for (const [name, path] of Object.entries(TEMPLATES)) {
  const content = readFileSync(path, 'utf-8')
  out += `export const ${name}_TEMPLATE: string = ${JSON.stringify(content)}\n\n`
}

writeFileSync(join(outDir, 'templates.ts'), out)
console.log('✓ Generated src/generated/templates.ts')
