/**
 * Shared helpers used by multiple generators.
 *
 * Keep this free of generator-specific logic — only primitives that two or
 * more generators would otherwise duplicate.
 */

import type { RepoFingerprint } from '../fingerprint/types.js'
import type { WorkflowConfig } from '../config/types.js'
import type { AISkill } from '../fingerprint/skills-builder.js'

// ─── Architecture style labels ────────────────────────────────────────────────

export const STYLE_LABELS: Record<string, string> = {
  cli:           'CLI tool',
  library:       'Library',
  monolith:      'Monolith',
  monorepo:      'Monorepo',
  microservices: 'Microservices',
}

// ─── Conventional commits detection ──────────────────────────────────────────

export function isConventionalCommits(fp: RepoFingerprint): boolean {
  return (
    fp.git?.commitStyle === 'conventional_commits' ||
    fp.conventions.some((c) => c.name === 'conventional_commits')
  )
}

// ─── Workflow rule lines ──────────────────────────────────────────────────────

/**
 * Returns the workflow rule bullet lines for a given WorkflowConfig.
 * Returns an empty array when all settings are 'never'.
 * Callers are responsible for wrapping lines in section markers / headings.
 */
export function buildWorkflowRuleLines(workflow: WorkflowConfig): string[] {
  const lines: string[] = []

  if (workflow.autoDocs === 'always') {
    lines.push('- **Documentation**: After adding or updating a feature, always update README.md and any relevant documentation files before marking the task complete.')
  } else if (workflow.autoDocs === 'ask') {
    lines.push('- **Documentation**: After adding or updating a feature, ask the user whether documentation (README.md, docs/) should be updated before finishing.')
  }

  if (workflow.autoCommit === 'always') {
    lines.push('- **Commits**: After completing a feature or fix, stage the relevant changed files and create a git commit with an appropriate message.')
  } else if (workflow.autoCommit === 'ask') {
    lines.push('- **Commits**: After completing a task, ask the user if they want to commit the changes.')
  }

  return lines
}

// ─── Skill file builders ────────────────────────────────────────────────────

/**
 * Render `.claude/skills.md` — index grouped by category, sorted alphabetically.
 * When foreignSkills are provided, appends a separate foreign_skills section.
 */
export function buildSkillsOverview(skills: readonly AISkill[], foreignSkills: readonly string[] = []): string {
  // Group by category
  const groups = new Map<string, AISkill[]>()
  for (const skill of skills) {
    const group = groups.get(skill.category) ?? []
    group.push(skill)
    groups.set(skill.category, group)
  }

  const sortedCategories = [...groups.keys()].sort()

  const lines: string[] = [
    '<!-- openskulls:section:skills -->',
    '# Project Skills',
    '',
    '> Auto-generated — run `openskulls sync` to update.',
    '> Each skill lives at `.claude/skills/<id>/SKILL.md` and is available as a `/<id>` slash command.',
  ]

  for (const category of sortedCategories) {
    const categorySkills = groups.get(category)!.slice().sort((a, b) => a.id.localeCompare(b.id))
    const categoryTitle = category.charAt(0).toUpperCase() + category.slice(1)

    lines.push('', `## ${categoryTitle}`)

    for (const skill of categorySkills) {
      lines.push('', `### ${skill.title}`, `\`/${skill.id}\` — ${skill.description}`)
    }
  }

  lines.push('', '<!-- /openskulls:section:skills -->')

  if (foreignSkills.length > 0) {
    lines.push('\n<!-- openskulls:section:foreign_skills -->')
    lines.push('## Manually Maintained Skills')
    lines.push('')
    lines.push('> These files exist in `.claude/commands/` but are not managed by openskulls.')
    lines.push('')
    for (const p of foreignSkills) lines.push(`- \`${p}\``)
    lines.push('')
    lines.push('<!-- /openskulls:section:foreign_skills -->')
  }

  return lines.join('\n')
}

/**
 * Render `.claude/skills/<id>/SKILL.md`.
 *
 * YAML frontmatter: name (slash command id) + multi-line trigger description.
 * Body: rich markdown reference document generated by AI.
 */
export function buildSkillFile(skill: AISkill): string {
  const lines = [
    '---',
    `name: ${skill.id}`,
    'description: >',
    // Indent the description block under the YAML folded scalar
    ...skill.description.split('. ').map((s) => `  ${s.trim()}${s.endsWith('.') ? '' : '.'}`),
    '---',
    '',
    skill.content,
  ]
  return lines.join('\n')
}
