/**
 * openskulls uninstall — clean up a repository.
 *
 * Removes what openskulls wrote to the repo:
 *   - The post-commit git hook (if installed by openskulls)
 *   - .openskulls/ directory (fingerprint, config, lockfile)
 *   - .claude/commands/ skill files (if generated by openskulls)
 *   - .claude/settings.json (if generated by openskulls)
 *   - CLAUDE.md openskulls sections, or the whole file
 *
 * Nothing is deleted without confirmation unless --yes is passed.
 * The binary itself is NOT removed — use the uninstall.sh script for that.
 */

import { createInterface } from 'node:readline/promises'
import { existsSync } from 'node:fs'
import { readFile, rm, writeFile } from 'node:fs/promises'
import { join, resolve } from 'node:path'
import type { Command } from 'commander'
import { divider, fatal, heading, log, panel } from '../ui/console.js'

const HOOK_MARKER = '# managed by openskulls'

export function registerUninstall(program: Command): void {
  program
    .command('uninstall [path]')
    .description('Remove openskulls-generated files from a repository')
    .option('-y, --yes', 'Skip confirmation prompts')
    .option('--keep-claude-md', 'Strip openskulls sections from CLAUDE.md instead of removing it')
    .action(async (
      path: string = '.',
      options: { yes?: boolean; keepClaudeMd?: boolean },
    ) => {
      const repoRoot = resolve(path)

      panel('OpenSkulls uninstall', [repoRoot])

      // ── Discover what exists ─────────────────────────────────────────────

      const targets: Array<{ label: string; path: string; action: 'delete' | 'strip' }> = []

      const hookPath      = join(repoRoot, '.git', 'hooks', 'post-commit')
      const openskulisDir = join(repoRoot, '.openskulls')
      const claudeMdPath  = join(repoRoot, 'CLAUDE.md')
      const claudeDir     = join(repoRoot, '.claude')

      if (existsSync(hookPath) && await isManagedHook(hookPath)) {
        targets.push({ label: '.git/hooks/post-commit', path: hookPath, action: 'delete' })
      }

      if (existsSync(openskulisDir)) {
        targets.push({ label: '.openskulls/', path: openskulisDir, action: 'delete' })
      }

      if (existsSync(claudeDir)) {
        targets.push({ label: '.claude/', path: claudeDir, action: 'delete' })
      }

      if (existsSync(claudeMdPath)) {
        if (options.keepClaudeMd) {
          targets.push({ label: 'CLAUDE.md (strip managed sections)', path: claudeMdPath, action: 'strip' })
        } else {
          targets.push({ label: 'CLAUDE.md', path: claudeMdPath, action: 'delete' })
        }
      }

      if (targets.length === 0) {
        log.info('Nothing to remove — no openskulls files found in this repo.')
        process.exit(0)
      }

      // ── Show plan ────────────────────────────────────────────────────────

      heading('Will remove')
      for (const t of targets) {
        log.warn(t.label)
      }
      log.blank()

      // ── Confirm ──────────────────────────────────────────────────────────

      if (!options.yes) {
        const rl = createInterface({ input: process.stdin, output: process.stdout })
        const answer = await rl.question('Proceed? [y/N] ')
        rl.close()
        if (answer.trim().toLowerCase() !== 'y') {
          log.info('Aborted.')
          process.exit(0)
        }
      }

      // ── Execute ──────────────────────────────────────────────────────────

      log.blank()
      for (const t of targets) {
        try {
          if (t.action === 'delete') {
            await rm(t.path, { recursive: true, force: true })
            log.success(`Removed ${t.label}`)
          } else {
            await stripManagedSections(t.path)
            log.success(`Stripped managed sections from ${t.label}`)
          }
        } catch (err) {
          fatal(`Failed to remove ${t.label}`, err instanceof Error ? err.message : String(err))
        }
      }

      log.blank()
      divider()
      log.success('Repository cleaned. To remove the openskulls binary:')
      log.info('  curl -fsSL https://raw.githubusercontent.com/klaptorsk/openskulls/main/uninstall.sh | sh')
    })
}

// ── Helpers ───────────────────────────────────────────────────────────────────

async function isManagedHook(hookPath: string): Promise<boolean> {
  try {
    const content = await readFile(hookPath, 'utf-8')
    return content.includes(HOOK_MARKER)
  } catch {
    return false
  }
}

/**
 * Remove all openskulls-tagged sections from a CLAUDE.md file,
 * preserving all manually authored content.
 */
async function stripManagedSections(filePath: string): Promise<void> {
  const content = await readFile(filePath, 'utf-8')
  const stripped = content.replace(
    /<!--\s*openskulls:section:[^\s>]+\s*-->[\s\S]*?<!--\s*\/openskulls:section:[^\s>]+\s*-->\n?/g,
    '',
  )
  await writeFile(filePath, stripped.trimStart(), 'utf-8')
}
